name: Devbox Update

on:
  schedule:
    - cron: "0 1 * * *" # daily: go directive aligned every day, full devbox update on Monday (mode auto)
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update:
    uses: truvity/ci-workflows/.github/workflows/devbox-update.yaml@9a25893002065e1502fc2957252a67b9892af71d # v2.12.3
    secrets: inherit
