name: Devbox Update

on:
  schedule:
    - cron: "0 1 * * *" # daily: go directive aligned every day, full devbox update on Monday (mode auto)
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update:
    uses: truvity/ci-workflows/.github/workflows/devbox-update.yaml@367635e4cd8312c449772fe8e43e6a7afe4f3bf9 # v2.19.0
    secrets: inherit
