name: Devbox Update

on:
  schedule:
    - cron: "0 1 * * *" # daily: go directive aligned every day, full devbox update on Monday (mode auto)
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update:
    uses: truvity/ci-workflows/.github/workflows/devbox-update.yaml@681547390267ac3474ffed005d0723a9dd202b3d # v2.12.2
    secrets: inherit
