name: Security

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 6 * * *" # daily 6am UTC

permissions:
  contents: read

jobs:
  govulncheck:
    uses: truvity/ci-workflows/.github/workflows/check.yaml@36be6b238bfb119de3ffeed9604bae5e7a3d7c8d # v3.4.0
    with:
      recipes: '["vuln"]'
