name: Security

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 6 * * *" # daily 6am UTC

permissions:
  contents: read

jobs:
  govulncheck:
    uses: truvity/ci-workflows/.github/workflows/check.yaml@02d66a9a2d64fe255d7703a1bebd764d0899f187 # v3.16.0
    with:
      recipes: '["vuln"]'
